hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon &")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("swayosd-server &")
    hl.exec_cmd("hyprsunset -t 4500 &")
    hl.exec_cmd("hypridle &")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
end)
