-- hyprland.lua
-- Generated by hypr-migrate from: hyprland.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       1 resolved
--   Config keys:     1 emitted
--   Monitors:        1
--   Keybinds:        1 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   2
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   11  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local configDir = "~/.config/hypr"

-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.environment")  -- was: source = ~/.config/hypr/environment.conf
require("~..config.hypr.environment")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.programs")  -- was: source = ~/.config/hypr/programs.conf
require("~..config.hypr.programs")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.input")  -- was: source = ~/.config/hypr/input.conf
require("~..config.hypr.input")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.colors")  -- was: source = ~/.config/hypr/colors.conf
require("~..config.hypr.colors")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.looknfeel")  -- was: source = ~/.config/hypr/looknfeel.conf
require("~..config.hypr.looknfeel")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.layers")  -- was: source = ~/.config/hypr/layers.conf
require("~..config.hypr.layers")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.animations.current_animations")  -- was: source = ~/.config/hypr/animations/current_animations.conf
require("~..config.hypr.animations.current_animations")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.windowrule")  -- was: source = ~/.config/hypr/windowrule.conf
require("~..config.hypr.windowrule")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.keybinds")  -- was: source = ~/.config/hypr/keybinds.conf
require("~..config.hypr.keybinds")
-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require(".home.bukh0..config.hypr.hyprland-gui")  -- was: source = /home/bukh0/.config/hypr/hyprland-gui.conf
require(".home.bukh0..config.hypr.hyprland-gui")

hl.config({
    decoration = {
        screen_shader = "",
    },
})

-- MIGRATION_NOTE: Empty monitor output — Hyprland may ignore this entry
hl.monitor({ output = "", position = "auto" })

hl.bind(" + switch:on:Lid Switch", function()
    hl.exec_cmd("hyprlock")
end), { locked = true }

hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
